# Generated by Django 5.0.4 on 2024-05-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sucursal', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=50)),
                ('precio_costo', models.FloatField()),
                ('precio_venta', models.FloatField()),
                ('existencias', models.IntegerField()),
                ('codigo_de_barras', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sucursal', models.CharField(max_length=50)),
            ],
        ),
    ]
