# Generated by Django 5.0.4 on 2024-05-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sucursales', '0002_listaventas_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
