# Generated by Django 5.0.4 on 2024-05-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sucursales', '0003_venta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaventas',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
